### ISSUE TITLE
Typo in run_before_squash.sh

### ISSUE THREAD

**Issue by jeremiahputnam** [killajoe/EndeavourOS-ISO-KDE#1]
It looks like there is a typo on line 92 of the run_before_squash script.

`rm "# Set wallpaper for live-session and original for installed system`

Typo with the rm " ?

**Comment by killajoe** [comment]
Uff thanks for the hint not a type more some paste overwrite.. will fix this later

**Comment by killajoe** [comment]
https://github.com/killajoe/EndeavourOS-ISO-KDE/commit/c4b4c77043cdeace8ba2d56e495846b3dc975b86
